upadte authentification to datadome api from query param to using the…
DataDome/terraform-provider-datadome pull request #15
Opened 2023-09-20 15:21 UTC by Simoouqas

… header

2023-10-11 12:25 UTC, Simoouqas commented
Please do not merge until the linked dashboard ticket is deployed

2023-10-11 14:05 UTC, BastienLedon requested changes

2023-10-11 14:05 UTC, BastienLedon commented on datadome-client-go/client.go
> +	q.Add("withoutTraffic", c.Token)
That doesn't seems ok. Why "value" and why do you send the token in the query param without Traffic ?

2023-10-12 10:20 UTC, Lauredg commented
Hello @Simoouqas ,
The integration team has just acquired responsibility for this provider, as it is a customer facing component.
Could you please update the description to give me some context and link the Jira ticket so that I can review your PR? Thanks a lot!

2023-10-12 13:04 UTC, Lauredg reviewed
LGTM! However I would like to test it before merging it. 
When the API change is in production, we will test it, merge it and then I will make the release if that's ok with you @Simoouqas .

2023-12-08 08:56 UTC, emmanuelCarre approved these changes
LGTM :+1: 

@Lauredg : have you test  it?

2023-12-13 10:44 UTC, Lauredg approved these changes

2023-12-13 10:44 UTC, Lauredg commented
@emmanuelCarre @Simoouqas I just tested it and it works :) 
I am going to merge it as it will solve https://github.com/DataDome/terraform-provider-datadome/issues/12

2023-12-13 13:23 UTC, BastienLedon approved these changes

2023-12-13 13:27 UTC, merged